name: Check CR

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # 1. generate cr.json
  # 2. diff against the latest
  # 3. if difference with them, release
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      # - name: Get Latest Release
      #   run: gh release download latest -p 'cr/*.json' # FIXME: filename
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Diff
      #   run:

      - name: Generate CR
        run: npm run gen_cr -- ./data/cr

      - name: Release
        run: gh release create v0.0.1 ./data/cr/*.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
